namespace: ansible
name: windows
version: 1.0.0
readme: README.md
authors: null
description: null
license: GPL-3.0-or-later
license_file: null
tags: null
dependencies: {}
repository: git@github.com:ansible-collection-migration/ansible.windows.git
documentation: https://github.com/ansible-collection-migration/ansible.windows/tree/master/docs
homepage: https://github.com/ansible-collection-migration/ansible.windows
issues: https://github.com/ansible-collection-migration/ansible.windows/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
